// Package hooks installs the docket's global git hook shims and handles the
// events they report. A global core.hooksPath replaces every repo's own hook
// directory, so there is a shim for every hook name git runs: each one records
// (for the hooks the docket journals) and then runs the hook git would have
// run without the docket, returning that hook's exit status.
package hooks

import (
	"fmt"
	"strings"
)

// Names lists every hook that gets a shim. Left out on purpose, because the
// mere presence of the file changes git's behavior: push-to-checkout,
// proc-receive, fsmonitor-watchman and the p4-* hooks.
var Names = []string{
	"applypatch-msg", "pre-applypatch", "post-applypatch",
	"pre-commit", "pre-merge-commit", "prepare-commit-msg", "commit-msg", "post-commit",
	"pre-rebase", "post-checkout", "post-merge", "pre-push", "pre-auto-gc", "post-rewrite",
	"sendemail-validate", "post-index-change", "reference-transaction",
	"pre-receive", "update", "post-receive", "post-update",
}

// recorded hooks are journaled; stdinHooks among them get their stdin copied
// so both the docket and the chained hook see it.
var (
	recorded   = map[string]bool{"reference-transaction": true, "pre-push": true, "post-checkout": true, "post-merge": true, "post-rewrite": true, "post-commit": true}
	stdinHooks = map[string]bool{"reference-transaction": true, "pre-push": true, "post-rewrite": true}
)

func shq(s string) string { return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'" }

// Shim renders the POSIX sh shim for hook name. binary is the docket
// executable; prev is the global core.hooksPath that was set before install
// ("" = each repo's own hooks directory).
func Shim(name, binary, prev string) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "#!/bin/sh\n# docket hook shim for %s: generated by `docket hooks install`; do not edit.\n", name)
	b.WriteString("# Records the event (output discarded, never blocks), then runs the hook git\n# would have run without docket and returns its exit status.\n")
	fmt.Fprintf(&b, "docket=%s\nprev=%s\ntmp=\n", shq(binary), shq(prev))
	if recorded[name] {
		b.WriteString("if [ -z \"$DOCKET_DISABLE\" ] && [ -z \"$DOCKET_INTERNAL\" ] && [ -x \"$docket\" ]; then\n")
		cond := ""
		if name == "reference-transaction" {
			cond = "  if [ \"$1\" = committed ]; then\n"
			b.WriteString(cond)
		}
		if stdinHooks[name] {
			fmt.Fprintf(&b, "  tmp=$(mktemp \"${TMPDIR:-/tmp}/docket-hook.XXXXXX\" 2>/dev/null) || tmp=\n")
			fmt.Fprintf(&b, "  if [ -n \"$tmp\" ]; then\n    cat >\"$tmp\"\n    \"$docket\" hook %s \"$@\" <\"$tmp\" >/dev/null 2>&1 || :\n  fi\n", name)
		} else {
			fmt.Fprintf(&b, "  \"$docket\" hook %s \"$@\" </dev/null >/dev/null 2>&1 || :\n", name)
		}
		if cond != "" {
			b.WriteString("  fi\n")
		}
		b.WriteString("fi\n")
	}
	fmt.Fprintf(&b, "if [ -n \"$prev\" ]; then\n  hook=\"$prev/%s\"\nelse\n  hook=\"$(git rev-parse --git-common-dir 2>/dev/null)/hooks/%s\"\nfi\n", name, name)
	b.WriteString("if [ -n \"$tmp\" ]; then\n  rc=0\n  if [ -f \"$hook\" ] && [ -x \"$hook\" ]; then\n    \"$hook\" \"$@\" <\"$tmp\"\n    rc=$?\n  fi\n  rm -f \"$tmp\"\n  exit $rc\nfi\n")
	b.WriteString("if [ -f \"$hook\" ] && [ -x \"$hook\" ]; then\n  exec \"$hook\" \"$@\"\nfi\nexit 0\n")
	return []byte(b.String())
}
