package serve

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"
	"time"
)

// THE WIRE HAS A TYPE, AND THE TYPE IS GENERATED BY A GO TEST — NOT A NODE
// SCRIPT.
//
// `pending.suggestions` was renamed (the galley lesson): one side changed and
// the other was never told, browser gates died, nobody noticed for weeks.
// The fix lives here, in `go test`, which is what `just verify` is made of:
// Go-only, always run, in CI and in the pre-push hook, on every machine.
//
// It writes the declarations from the structs' own json tags and diffs them
// against the committed web/wire.d.ts, failing with the same "run X and commit
// the result" message the editor-bundle staleness check already uses — so the
// fix is legible from the message alone.

// updateWire rewrites web/wire.d.ts instead of asserting it. `go test ./internal/casebook/serve/ -run TestTheWireTypeIsCommitted -update`.
var updateWire = flag.Bool("update", false, "rewrite internal/casebook/web/wire.d.ts from the Go structs")

// wireRoots is THE CONTRACT: every view struct the browser reads off the
// casebook page API and the agent API. Adding a struct here is how a new
// endpoint's payload becomes a type the browser cannot silently disagree with.
//
// The order is the order they are emitted in: summary first (the page's first
// read), then list/item views, then mutation results, then agent views.
var wireRoots = []any{
	SummaryView{},
	ItemsView{},
	ItemDetailView{},
	DecideResult{},
	AcceptResult{},
	RejectResult{},
	SessionsView{},
	ThreadsView{},
	MessagesView{},
	SendBatchResult{},
	ResendResult{},
	WaitView{},
	ReplyResult{},
	ProposeResult{},
	StatusView{},
	OpenResult{},
	SettledResult{},
}

const wirePath = "../web/wire.d.ts"

func TestTheWireTypeIsCommitted(t *testing.T) {
	want := generateWire()
	if *updateWire {
		if err := os.MkdirAll(filepath.Dir(filepath.Clean(wirePath)), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Clean(wirePath), []byte(want), 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("wrote %s", wirePath)
		return
	}
	got, err := os.ReadFile(filepath.Clean(wirePath))
	if err != nil {
		t.Fatalf("the wire declarations are missing (%v) — run `go test ./internal/casebook/serve/ -run TestTheWireTypeIsCommitted -update` and commit the result", err)
	}
	if string(got) != want {
		t.Errorf("the committed internal/casebook/web/wire.d.ts does not match the Go structs — run `go test ./internal/casebook/serve/ -run TestTheWireTypeIsCommitted -update` and commit the result\n\n%s",
			firstDifference(string(got), want))
	}
}

// firstDifference names the line that moved, because a whole-file diff of a
// generated declaration file is unreadable in a test log and the ONE thing the
// reader needs is which field changed.
func firstDifference(got, want string) string {
	g, w := strings.Split(got, "\n"), strings.Split(want, "\n")
	for i := 0; i < len(g) || i < len(w); i++ {
		var gl, wl string
		if i < len(g) {
			gl = g[i]
		}
		if i < len(w) {
			wl = w[i]
		}
		if gl != wl {
			return fmt.Sprintf("first difference at line %d:\n  committed: %q\n  generated: %q", i+1, gl, wl)
		}
	}
	return "(files differ only in length)"
}

// generateWire renders the whole declaration file.
//
// HOW FAR A REFERENCE IS FOLLOWED: as far as it goes. A field whose type is a
// struct — in THIS package or any other, named or pointed at or sliced — is
// emitted as its own interface and its own fields are walked in turn. The one
// terminal struct is time.Time, which marshals to an RFC3339 string.
func generateWire() string {
	var b strings.Builder
	b.WriteString(wireHeader)

	seen := map[reflect.Type]bool{}
	var queue []reflect.Type
	for _, root := range wireRoots {
		rt := reflect.TypeOf(root)
		if !seen[rt] {
			seen[rt] = true
			queue = append(queue, rt)
		}
	}
	// Breadth-first from the roots so the contract structs come first and
	// anything they reach follows in the order it was reached.
	for i := 0; i < len(queue); i++ {
		t := queue[i]
		b.WriteString("\n")
		b.WriteString(renderInterface(t, func(dep reflect.Type) {
			if !seen[dep] {
				seen[dep] = true
				queue = append(queue, dep)
			}
		}))
	}
	return b.String()
}

func renderInterface(t reflect.Type, found func(reflect.Type)) string {
	var b strings.Builder
	fmt.Fprintf(&b, "export interface %s {\n", tsName(t))
	renderFields(&b, t, found)
	b.WriteString("}\n")
	return b.String()
}

// renderFields emits each exported field of t. Anonymous (embedded) struct
// fields are inlined — encoding/json promotes them the same way, so the
// TypeScript declaration must flatten them too or the shape is wrong.
func renderFields(b *strings.Builder, t reflect.Type, found func(reflect.Type)) {
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if f.PkgPath != "" {
			continue // unexported: encoding/json never writes it
		}
		name, opts := jsonName(f)
		if name == "-" {
			continue
		}
		if f.Anonymous {
			// Embedded struct: encoding/json promotes its fields to the parent
			// level. Inline them here rather than emitting a named field.
			ft := f.Type
			if ft.Kind() == reflect.Pointer {
				ft = ft.Elem()
			}
			if ft.Kind() == reflect.Struct {
				renderFields(b, ft, found)
			}
			continue
		}
		typ := tsType(f.Type, found)
		optional := ""
		if opts.omitempty {
			optional = "?"
		} else if nullable(f.Type) {
			typ += " | null"
		}
		fmt.Fprintf(b, "  %s%s: %s;\n", name, optional, typ)
	}
}

func nullable(t reflect.Type) bool {
	switch t.Kind() {
	case reflect.Slice, reflect.Map, reflect.Pointer, reflect.Interface:
		return true
	}
	return false
}

var timeType = reflect.TypeOf(time.Time{})

func tsType(t reflect.Type, found func(reflect.Type)) string {
	if t == timeType {
		return "string"
	}
	switch t.Kind() {
	case reflect.Pointer:
		return tsType(t.Elem(), found)
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	case reflect.Slice, reflect.Array:
		return tsType(t.Elem(), found) + "[]"
	case reflect.Map:
		return fmt.Sprintf("Record<%s, %s>", tsType(t.Key(), found), tsType(t.Elem(), found))
	case reflect.Struct:
		found(t)
		return tsName(t)
	default:
		return "unknown"
	}
}

// tsName is the Go type's own name with an exported first letter.
func tsName(t reflect.Type) string {
	n := t.Name()
	if n == "" {
		return "unknown"
	}
	return strings.ToUpper(n[:1]) + n[1:]
}

type jsonOpts struct{ omitempty bool }

func jsonName(f reflect.StructField) (string, jsonOpts) {
	tag := f.Tag.Get("json")
	if tag == "" {
		return f.Name, jsonOpts{}
	}
	parts := strings.Split(tag, ",")
	name := parts[0]
	if name == "" {
		name = f.Name
	}
	var o jsonOpts
	for _, p := range parts[1:] {
		if p == "omitempty" {
			o.omitempty = true
		}
	}
	return name, o
}

// TestTheWireGeneratorFollowsCrossPackageReferences checks that the generator
// reaches types from other packages (deliver, propose, journal, etc.) —
// "as far as it goes" is a behaviour claim the golden file alone cannot prove.
// It also checks that embedded struct fields are promoted (ItemView inlines
// engine.Item's fields rather than emitting a named "Item" field).
func TestTheWireGeneratorFollowsCrossPackageReferences(t *testing.T) {
	out := generateWire()
	for _, want := range []string{
		"export interface Delivery {",       // deliver.Delivery, reached through WaitView
		"export interface Proposal {",       // propose.Proposal, reached through ProposeResult
		"export interface Session {",        // deliver.Session, reached through SessionsView
		"export interface Thread {",         // deliver.Thread, reached through ThreadsView
		"export interface Event {",          // journal.Event, reached through ItemDetailView
		"export interface SkippedMessage {", // deliver.SkippedMessage, reached through ReplyResult
		"messages: Message[] | null;",       // inside Delivery
		"sessions: Session[] | null;",       // inside SessionsView
		"key: string;",                      // engine.Item.ID promoted into ItemView
		"status: string;",                   // engine.Item.Status promoted into ItemView
		"proposal?: Proposal;",              // ItemView.Proposal (explicit field)
	} {
		if !strings.Contains(out, want) {
			t.Errorf("generated wire.d.ts is missing %q", want)
		}
	}
	if strings.Contains(out, ": any") {
		t.Error("the generated wire carries `any`")
	}
	if n := strings.Count(out, "unknown"); n != 0 {
		lines := []string{}
		for _, l := range strings.Split(out, "\n") {
			if strings.Contains(l, "unknown") {
				lines = append(lines, strings.TrimSpace(l))
			}
		}
		sort.Strings(lines)
		t.Errorf("the generated wire carries %d unknown field(s): %v", n, lines)
	}
}

const wireHeader = `// wire.d.ts — THE GO↔JS CONTRACT, GENERATED. DO NOT EDIT.
//
// Written by internal/casebook/serve/wire_test.go from the json tags of every
// view struct returned by the casebook page API and agent API. Adding a struct
// to wireRoots is how a new endpoint's payload becomes a type the browser
// cannot silently disagree with.
//
// Regenerate with ` + "`go test ./internal/casebook/serve/ -run TestTheWireTypeIsCommitted -update`" + ` and commit.
// Drift fails ` + "`just verify`" + ` (Go-only, always run in CI and the pre-push hook).
//
// READING THE OPTIONALITY:
//
//   - ` + "`x?: T`" + ` — the Go field carries ` + "`omitempty`" + `, so the key is ABSENT from
//     the payload when it is the zero value.
//   - ` + "`x: T[] | null`" + ` — no ` + "`omitempty`" + `, so a nil slice is serialized as JSON
//     ` + "`null`" + `. The type says so rather than promising an array.
//   - a ` + "`time.Time`" + ` is a string (RFC3339). It is not a shape on the wire.
`
